import type { MenuItem } from '../types';

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Chicken Biryani',
    description: 'Aromatic basmati rice cooked with tender chicken pieces and exotic spices',
    price: 280,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAvM8isNBTfSmtYZshzOUNQMtPHxjD-4sgfs3q4jLaQYxgHaeEzbuRB_zD49oW3egMgtVDFVyBkB75S8XJk-52JZALe7EJFabCHR9aZoiajKV6gdcvPQJugnfK9T4-HszJ3nrHpyTEV4-R1fgMeIrbxrk-FNNjc1MyxZdrLEMQP_ywHXtTvk2blvzHaCR-4RNkGG8hLRhk_KLl3B8z9uNYIMDvESFwFqF60JLu-jM1ld02NS5V80-g5tP6pmELh8-0tUf0BiVctLF8',
    category: 'Main Course',
    isVegetarian: false,
    isPopular: true,
    restaurantId: '1',
  },
  {
    id: '2',
    name: 'Paneer Butter Masala',
    description: 'Soft cottage cheese cubes in rich, creamy tomato-based gravy',
    price: 220,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDJWSBuGbTn8YQJnn-b94bZrZtG2FeXjTKaK7q7RnbrpWsKgY2eKBHeBI8TENkA4SCf3Q_H5AM1H0Pfel9PKRKHXixkTrTV6Q2nsGOYGsAuPV1lhWBow2CWHyc4i82_SmySL6C3XRF-H5IelYR-dFuWJ7qEg4NPi2yq92DH9N4xJJ7WfFUUXvbR7atwyqgRjQ4p5UxHa8S7BGsgCSV20A61JlwtyJa4E9AZlEAjVqSJ2wHZsTVGkx5lYUl_Kf-ZyY8nWqsLwKofd5Y',
    category: 'Main Course',
    isVegetarian: true,
    isPopular: true,
    restaurantId: '1',
  },
  {
    id: '3',
    name: 'Veg Spring Rolls',
    description: 'Crispy rolls filled with fresh vegetables and served with sweet chili sauce',
    price: 120,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAnFMunN5QWUlrC4rvH8iuKjFGF-dacC2Lt_c5CMQjcJRNC-4PWvmkJsOIH_4jIZX35Hpl92ry_SG3crYQImYkcHqd_irlGB6BLqoYiNI03FvuDaMIsrqy3E8VWehy7Eq8iSbZGNXN3UhqnrsnWJoBp3JZ7SCI3sAOe86LiXSY9AOqb5lTqEHmU5mvCL0JE2fbwPhdMaotSdvsck5u_ot_uAy6OA5bzVcr-ErDcfhRZ03N4blbFcLiO2o9SO15T2CNpDw6iVcW1tEU',
    category: 'Appetizers',
    isVegetarian: true,
    isPopular: false,
    restaurantId: '1',
  },
  {
    id: '4',
    name: 'Chicken Wings',
    description: 'Spicy chicken wings marinated in special herbs and grilled to perfection',
    price: 180,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBsnvUCb-CbcH4qOsNOWQtYhwKVXPizL7-XuWbtu_BLO0NbMby8s_EKXRNQWMgMnzebwK4Rh_9AstlhXnrjj6FYp5T4H-40xgJkRJk3z8CiWAJQm1kCCgbaB7cMSfZb8NqEnAMBuV9qARxQs6fhrHCdQRgZduvGdGm-i-X62WPD_6nB8A-NPrpzfhelt7WH_gQAfkpVAy-_Ova3i079oEeHdd--jSZEY-FkOxH7XcNYbsjlm8Yndmv7i6YXlbRTwcc3UDTvV4cvWm8',
    category: 'Appetizers',
    isVegetarian: false,
    isPopular: true,
    restaurantId: '1',
  },
  {
    id: '5',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with a molten chocolate center, served with vanilla ice cream',
    price: 150,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDPOFyFAo7au4ZrLIQv0e-uezeDtVftJoE2LSGIhYKK6clmHIC-rc_tUs3KbA1Imedvitoay-tiHBA1vQ4Wrim7LaXwUK48MXZiC8r-P_5g7cj_Apc-Psh1mli6zlQIazlH7i7tY-KQ1maB2yxqvECOHbO9UVQomq4eXYvSzXa321VmJbyvXvjwH_ADO1Y8tUVOfJ3x-Bt2JHAxCfZ9cXlLXikZjUJHB6j3uHBmP4DvzbhXK-zgsuc3oQwTGbNG7veKv-WaD3OgAao',
    category: 'Desserts',
    isVegetarian: true,
    isPopular: true,
    restaurantId: '1',
  },
  {
    id: '6',
    name: 'Gulab Jamun',
    description: 'Soft milk solids dumplings soaked in fragrant sugar syrup',
    price: 80,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCA5TLg_QZhTvsUiBrvCy4YoWmt4QIWTb_8kXd9PeRLuXDOJVGbnHu5mQ7eSoaJM2Xg_Wfu0lylmGR4-6kq5USVpRUSHBVvUK5PKazsLzFyoqxgkQPRAlo8XsOCz1O4FRIwaIQsX8-sKGRqSEBCG_7bs3U5OrBiMadtgZ4c1ggJOS13z3sCA9ajjYMSvaozbxoPWfnwQVmysodUNS25Ne5mwSWiaKFO8hQryOOJzwlJOhlY3NQe2fpaF_M1lUv6lOFsSVi2DNphUGU',
    category: 'Desserts',
    isVegetarian: true,
    isPopular: false,
    restaurantId: '1',
  },
  {
    id: '7',
    name: 'Mutton Rogan Josh',
    description: 'Tender mutton pieces cooked in aromatic Kashmiri spices and yogurt gravy',
    price: 320,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCp6_ZgGxm5EczR9hDwCnVTN-1SGLpMkLIH-ZuB-XPGPyGneBa5STLmWfonCIJ8J3NOWkE3V5xJzpUPIEn7KrA8IGXa_1v54MuckP0rYl4F-BCwTM7nWb7YBkmZ6zlZlJ2Ixhw_z86jOMuCiK0Z5T_wEA0epcZbZmX6Qutnl6P1MQNingsE_oQlusftckAB12HMV2eYSLnlbYgnWYNuXitmq_QPGWHI3rbpOXNhKNTx6unVAO-XW4Y_KJgXAjBDkOMmcEw0NW0FP9o',
    category: 'Main Course',
    isVegetarian: false,
    isPopular: false,
    restaurantId: '1',
  },
  {
    id: '8',
    name: 'Dal Makhani',
    description: 'Creamy black lentils slow-cooked with butter and aromatic spices',
    price: 180,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBilknx9nWGnbwW-oo2BbPOETZUfmX96kYzaqJSHN8E4U2mNC7GJVdsolCVBmAnEVasaPYwFptCRGvQZ2IaJdE4Pkd7avYqr09kmvVok4_Q3hOdfVXJqoNSWWhKNhoITrblfw-pm1Szt1NihxXLhNOV5BQwR4n99VJdspsQmE3VCljGLvgq9GvI1L7ZvjRFAJdexLZ2c6SmxQo3dX13gZ8aMzCGoqrOrY7h_NXrBJ_ADCVJVproZ3xuRt6GJUUKQ4755CnzI-Uzd_s',
    category: 'Main Course',
    isVegetarian: true,
    isPopular: false,
    restaurantId: '1',
  },
];
